services:
  - type: web
    name: codearena-backend
    env: node
    plan: free
    region: ohio
    buildCommand: npm install && cd backend && npx prisma generate
    startCommand: cd backend && (node src/server.js & node worker/worker.js)
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000
